hosts:
  - { ip: 10.1.6.119, name: apic-2_oob, mac: ""}
  - { ip: 10.1.17.59, name: cdo-sdc-01, mac: ""}
  - { ip: 10.1.17.58, name: se-r5-c240m4-07_cimc, mac: ""}
  - { ip: 10.1.17.55, name: gluster-mig, mac: ""}
  - { ip: 10.1.17.54, name: se-r5-c240m4-04, mac: ""}
  - { ip: 10.1.17.57, name: se-r5-c240m4-07, mac: ""}
  - { ip: 10.1.17.56, name: se-r5-c240m4-06, mac: ""}
  - { ip: 10.1.17.51, name: se-r5-c240m4-01, mac: ""}
  - { ip: 10.1.17.50, name: vcsa-01, mac: ""}
  - { ip: 10.1.17.53, name: se-r5-c240m4-03, mac: ""}
  - { ip: 10.1.17.52, name: se-r5-c240m4-02, mac: ""}
  - { ip: 10.1.18.14, name: se-r4_n9372px-e-02, mac: ""}
  - { ip: 10.1.18.15, name: se-r4_n92160yc-ex-01, mac: ""}
  - { ip: 10.1.18.16, name: se-r4_n92160yc-ex-02, mac: ""}
  - { ip: 10.1.18.70, name: sbr-r4_asa5585-02-admin, mac: ""}
  - { ip: 10.1.18.17, name: se-r4_n9236c-01, mac: ""}
  - { ip: 10.1.18.11, name: se-r4_n9372tx-e-01, mac: ""}
  - { ip: 10.1.17.61, name: candid-01, mac: ""}
  - { ip: 10.1.17.62, name: candid-02, mac: ""}
  - { ip: 10.1.17.63, name: candid-03, mac: ""}
  - { ip: 10.1.17.64, name: ise-01, mac: ""}
  - { ip: 10.1.17.65, name: ise-02, mac: ""}
  - { ip: 10.1.17.66, name: ise-03, mac: ""}
  - { ip: 10.1.17.67, name: tick-01, mac: ""}
  - { ip: 10.1.17.68, name: docker-01, mac: ""}
  - { ip: 10.1.17.69, name: docker-02, mac: ""}
  - { ip: 10.1.18.13, name: se-r4_n9372px-e-01, mac: ""}
  - { ip: 10.1.18.131, name: sec-ave-1001_oob, mac: ""}
  - { ip: 10.1.18.132, name: sec-ave-1002_oob, mac: ""}
  - { ip: 10.1.18.122, name: sec-leaf-2002_oob, mac: ""}
  - { ip: 10.1.18.3, name: se-r4_n9372px-e-mgmt_mgmt0, mac: ""}
  - { ip: 10.1.18.1, name: se-r4_n9372px-e-mgmt_vl-18, mac: ""}
  - { ip: 10.1.18.121, name: sec-leaf-2001_oob, mac: ""}
  - { ip: 10.1.18.60, name: se-r5_asa5585-01-admin, mac: ""}
  - { ip: 10.1.92.103, name: leaf-103_inb, mac: ""}
  - { ip: 10.20.4.12, name: stulab-asa, mac: ""}
  - { ip: 10.1.17.221, name: ucs-m_ext-mgmt_221, mac: ""}
  - { ip: 10.1.18.102, name: sec-spine-102_oob, mac: ""}
  - { ip: 10.1.17.73, name: ftd-03, mac: ""}
  - { ip: 10.1.17.72, name: ftd-02, mac: ""}
  - { ip: 10.1.17.71, name: ftd-01, mac: ""}
  - { ip: 10.1.18.106, name: leaf-106_oob, mac: ""}
  - { ip: 10.1.18.50, name: se-r5_asa5516-02-sfr, mac: ""}
  - { ip: 10.1.17.228, name: ucs-m_ext-mgmt_228, mac: ""}
  - { ip: 10.1.18.20, name: se-r4_n93180fx-02, mac: ""}
  - { ip: 10.1.18.111, name: sec-leaf-1001_oob, mac: ""}
  - { ip: 10.1.17.159, name: dhcp_vl-17_159, mac: ""}
  - { ip: 10.1.17.241, name: zfs-01, mac: ""}
  - { ip: 10.1.17.242, name: zfs-02, mac: ""}
  - { ip: 10.1.17.249, name: infra-02, mac: ""}
  - { ip: 10.1.17.248, name: infra-01, mac: ""}
  - { ip: 10.1.17.146, name: dhcp_vl-17_146, mac: ""}
  - { ip: 10.1.6.121, name: apic-3_oob, mac: ""}
  - { ip: 10.1.6.120, name: apic-1_oob, mac: ""}
  - { ip: 10.1.18.112, name: sec-leaf-1002_oob, mac: ""}
  - { ip: 10.1.17.147, name: dhcp_vl-17_147, mac: ""}
  - { ip: 10.1.92.1, name: aci_bd_vl-92, mac: ""}
  - { ip: 10.1.17.151, name: dhcp_vl-17_151, mac: ""}
  - { ip: 10.1.17.150, name: dhcp_vl-17_150, mac: ""}
  - { ip: 10.1.17.153, name: dhcp_vl-17_153, mac: ""}
  - { ip: 10.1.17.152, name: dhcp_vl-17_152, mac: ""}
  - { ip: 10.1.17.155, name: dhcp_vl-17_155, mac: ""}
  - { ip: 10.1.17.154, name: dhcp_vl-17_154, mac: ""}
  - { ip: 10.1.17.157, name: dhcp_vl-17_157, mac: ""}
  - { ip: 10.1.17.156, name: dhcp_vl-17_156, mac: ""}
  - { ip: 10.1.17.82, name: ftd-12, mac: ""}
  - { ip: 10.1.17.158, name: dhcp_vl-17_158, mac: ""}
  - { ip: 10.1.17.250, name: secfab-vl17-bd, mac: ""}
  - { ip: 10.1.17.81, name: ftd-11, mac: ""}
  - { ip: 10.1.18.49, name: se-r5_asa5516-01-sfr, mac: ""}
  - { ip: 10.1.18.48, name: se-r5_asa5516-02, mac: ""}
  - { ip: 10.1.17.1, name: se-r4_n9372px-e-mgmt_vl-17, mac: ""}
  - { ip: 10.1.17.227, name: ucs-m_ext-mgmt_227, mac: ""}
  - { ip: 10.1.92.101, name: leaf-101_inb, mac: ""}
  - { ip: 10.1.92.106, name: leaf-106_inb, mac: ""}
  - { ip: 10.1.92.105, name: leaf-105_inb, mac: ""}
  - { ip: 10.1.17.225, name: ucs-m_ext-mgmt_225, mac: ""}
  - { ip: 10.1.18.101, name: sec-spine-101_oob, mac: ""}
  - { ip: 10.1.17.224, name: ucs-m_ext-mgmt_224, mac: ""}
  - { ip: 10.1.18.202, name: spine-202_oob, mac: ""}
  - { ip: 10.1.18.201, name: mon-cougar, mac: ""}
  - { ip: 10.1.17.222, name: ucs-m_ext-mgmt_222, mac: ""}
  - { ip: 10.1.17.11, name: se-r4_fi-a, mac: ""}
  - { ip: 10.1.17.10, name: se-r4_ucsm, mac: ""}
  - { ip: 10.1.17.12, name: se-r4_fi-b, mac: ""}
  - { ip: 10.1.17.148, name: dhcp_vl-17_148, mac: ""}
  - { ip: 10.1.18.105, name: leaf-105_oob, mac: ""}
  - { ip: 10.1.17.149, name: dhcp_vl-17_149, mac: ""}
  - { ip: 10.1.17.99, name: fmc-99, mac: ""}
  - { ip: 10.1.17.98, name: fmc-98, mac: ""}
  - { ip: 10.1.17.144, name: dhcp_vl-17_144, mac: ""}
  - { ip: 10.1.17.145, name: dhcp_vl-17_145, mac: ""}
  - { ip: 10.1.17.142, name: dhcp_vl-17_142, mac: ""}
  - { ip: 10.1.17.143, name: dhcp_vl-17_143, mac: ""}
  - { ip: 10.1.17.140, name: dhcp_vl-17_140, mac: ""}
  - { ip: 10.1.17.141, name: dhcp_vl-17_141, mac: ""}
  - { ip: 10.1.17.91, name: ftd-91, mac: ""}
  - { ip: 10.1.17.226, name: ucs-m_ext-mgmt_226, mac: ""}
  - { ip: 10.1.17.93, name: ftd-93, mac: ""}
  - { ip: 10.1.17.92, name: ftd-92, mac: ""}
  - { ip: 10.1.17.223, name: ucs-m_ext-mgmt_223, mac: ""}
  - { ip: 10.1.17.94, name: ftd-94, mac: ""}
  - { ip: 10.1.17.97, name: fmc-97, mac: ""}
  - { ip: 10.1.17.96, name: fmc-96, mac: ""}
  - { ip: 10.1.18.32, name: se-r5_asr1001-hx-01, mac: ""}
  - { ip: 10.1.18.33, name: se-r5_isr4321-01, mac: ""}
  - { ip: 10.1.18.31, name: se-r5_asr1001-x-01, mac: ""}
  - { ip: 10.1.92.201, name: spine-201_inb, mac: ""}
  - { ip: 10.1.92.202, name: spine-202_inb, mac: ""}
  - { ip: 10.1.18.47, name: se-r5_asa5516-01, mac: ""}
  - { ip: 10.1.18.46, name: se-r4_n7702-01_vdc6, mac: ""}
  - { ip: 10.1.18.90, name: sbr-r4-fp4100-02-admin, mac: ""}
  - { ip: 10.1.18.45, name: se-r4_n7702-01_vdc5, mac: ""}
  - { ip: 10.1.17.24, name: win2k12-infra-02, mac: ""}
  - { ip: 10.1.17.25, name: grafana-01, mac: ""}
  - { ip: 10.1.17.26, name: script-01, mac: ""}
  - { ip: 10.1.17.27, name: fmc-01, mac: ""}
  - { ip: 10.1.17.21, name: ansible-01, mac: ""}
  - { ip: 10.1.17.22, name: syslog-01, mac: ""}
  - { ip: 10.1.17.23, name: win2k12-infra-01, mac: ""}
  - { ip: 10.1.18.43, name: se-r4_n7702-01_vdc3, mac: ""}
  - { ip: 10.1.17.28, name: se-r5_c220m4-02_cimc, mac: ""}
  - { ip: 10.1.17.29, name: sec-apic-01, mac: ""}
  - { ip: 10.1.18.42, name: se-r4_n7702-01_vdc2, mac: ""}
  - { ip: 10.1.18.41, name: se-r4_n7702-01_vdc1, mac: ""}
  - { ip: 10.1.92.13, name: apic-3_inb, mac: ""}
  - { ip: 10.1.18.40, name: se-r4_n7702-01, mac: ""}
  - { ip: 10.1.17.133, name: dhcp_vl-17_133, mac: ""}
  - { ip: 10.1.17.132, name: dhcp_vl-17_132, mac: ""}
  - { ip: 10.1.17.131, name: dhcp_vl-17_131, mac: ""}
  - { ip: 10.1.17.130, name: dhcp_vl-17_130, mac: ""}
  - { ip: 10.1.17.137, name: dhcp_vl-17_137, mac: ""}
  - { ip: 10.1.17.136, name: dhcp_vl-17_136, mac: ""}
  - { ip: 10.1.17.135, name: dhcp_vl-17_135, mac: ""}
  - { ip: 10.1.17.134, name: dhcp_vl-17_134, mac: ""}
  - { ip: 10.1.17.139, name: dhcp_vl-17_139, mac: ""}
  - { ip: 10.1.17.138, name: dhcp_vl-17_138, mac: ""}
  - { ip: 10.1.18.80, name: se-r5-fp4100-01-admin, mac: ""}
  - { ip: 10.1.17.39, name: sfcsf-01, mac: ""}
  - { ip: 10.1.17.38, name: smcve-02, mac: ""}
  - { ip: 10.1.17.199, name: aci_bd_vl-17, mac: ""}
  - { ip: 10.1.17.33, name: se-r5-c240m4-03_cimc, mac: ""}
  - { ip: 10.1.17.32, name: se-r5-c240m4-02_cimc, mac: ""}
  - { ip: 10.1.17.31, name: se-r5-c240m4-01_cimc, mac: ""}
  - { ip: 10.1.17.30, name: se-r5_c220m4-01_cimc, mac: ""}
  - { ip: 10.1.17.37, name: smcve-01, mac: ""}
  - { ip: 10.1.17.36, name: se-r5-c240m4-06_cimc, mac: ""}
  - { ip: 10.1.17.35, name: se-r4-aci-esx-01, mac: ""}
  - { ip: 10.1.17.34, name: se-r5-c240m4-04_cimc, mac: ""}
  - { ip: 10.1.92.12, name: apic-2_inb, mac: ""}
  - { ip: 10.1.17.220, name: ucs-m_ext-mgmt_220, mac: ""}
  - { ip: 10.1.92.11, name: apic-1_inb, mac: ""}
  - { ip: 10.1.18.44, name: se-r4_n7702-01_vdc4, mac: ""}
  - { ip: 10.1.17.201, name: mon-jester, mac: ""}
  - { ip: 10.1.17.115, name: dhcp_vl-17_115, mac: ""}
  - { ip: 10.1.17.202, name: prom-01, mac: ""}
  - { ip: 10.1.92.102, name: leaf-102_inb, mac: ""}
  - { ip: 10.1.7.37, name: sbr-r4-aci-esx-02, mac: ""}
  - { ip: 10.1.17.120, name: dhcp_vl-17_120, mac: ""}
  - { ip: 10.1.17.121, name: dhcp_vl-17_121, mac: ""}
  - { ip: 10.1.17.122, name: dhcp_vl-17_122, mac: ""}
  - { ip: 10.1.17.123, name: dhcp_vl-17_123, mac: ""}
  - { ip: 10.1.17.124, name: dhcp_vl-17_124, mac: ""}
  - { ip: 10.1.17.125, name: dhcp_vl-17_125, mac: ""}
  - { ip: 10.1.17.126, name: dhcp_vl-17_126, mac: ""}
  - { ip: 10.1.17.127, name: dhcp_vl-17_127, mac: ""}
  - { ip: 10.1.17.128, name: dhcp_vl-17_128, mac: ""}
  - { ip: 10.1.17.129, name: dhcp_vl-17_129, mac: ""}
  - { ip: 10.1.18.18, name: se-r4_n9236c-02, mac: ""}
  - { ip: 10.1.18.19, name: se-r4_n93180fx-01, mac: ""}
  - { ip: 10.1.18.12, name: se-r4_n9372tx-e-02, mac: ""}
  - { ip: 10.1.17.48, name: se-r5-c240m4-06_cimc, mac: ""}
  - { ip: 10.1.17.200, name: honey-01, mac: ""}
  - { ip: 10.1.17.46, name: zabbix-01, mac: ""}
  - { ip: 10.1.17.47, name: se-r5-c240m4-05_cimc, mac: ""}
  - { ip: 10.1.17.44, name: samba-01, mac: ""}
  - { ip: 10.1.17.45, name: samba-02, mac: ""}
  - { ip: 10.1.17.40, name: sfcnf-01, mac: ""}
  - { ip: 10.1.17.41, name: sona-01, mac: ""}
  - { ip: 10.1.7.35, name: sbr-r4-aci-esx-01, mac: ""}
  - { ip: 10.1.17.114, name: dhcp_vl-17_114, mac: ""}
  - { ip: 10.1.17.117, name: dhcp_vl-17_117, mac: ""}
  - { ip: 10.1.17.116, name: dhcp_vl-17_116, mac: ""}
  - { ip: 10.1.17.113, name: dhcp_vl-17_113, mac: ""}
  - { ip: 10.1.17.112, name: dhcp_vl-17_112, mac: ""}
  - { ip: 10.1.17.119, name: dhcp_vl-17_119, mac: ""}
  - { ip: 10.1.17.118, name: dhcp_vl-17_118, mac: ""}
